### ISSUE TITLE
could you tell me the format of how to run?

### ISSUE THREAD

**Issue by daixiongming** [vojirt/kcf#3]
I fail to run:
./kcf_vot region.txt images.txt
 the region.txt have 4 numbers:246,226,94,114,
the images.txt is the absolute path of images:/home/daixiongming/下载/kcf-master/build_dai/blurFace/img.

the blurFace is downloaded on visual tracker benchmark!

but I also fail to run!!!!could you give me some advice ????thanks.

**Comment by vojirt** [comment]
the file names are hardcoded so they do not need to be passed as argument.
if current working directory is e.g. ~/work
then ~/work/region.txt contains 246,226,94,114
and ~/work/images.txt contains
/home/daixiongming/下载/kcf-master/build_dai/blurFace/img/image01.jpg
/home/daixiongming/下载/kcf-master/build_dai/blurFace/img/image02.jpg
/home/daixiongming/下载/kcf-master/build_dai/blurFace/img/image03.jpg
etc... (replace imageXX.jpg by actual names of images) 

then run in directory ~/work/
./kcf_vot

For further question, please use email communications, since this is not a code issue!
