### ISSUE TITLE
What is the principle of this function——cv::Point2f KCF_Tracker::sub_pixel_peak？

### ISSUE THREAD

**Issue by dafeige01** [vojirt/kcf#32]
Hi，I wonder the principle of the  function " cv::Point2f KCF_Tracker::sub_pixel_peak(cv::Point & max_loc, cv::Mat & response) " in track.cpp. How does it work? It seems that there is no this step in the original paper. Many thanks!

**Comment by vojirt** [comment]
Hi, it finds sub pixel location of the maximum response in the correlation map by fitting polynomial (of second order) to the neighbourhood of the pixel-level maximum location. For example, consider 1D case, you have 
responses  : 1 2 2 3 1  
at locations: 0 1 2 3 4
pixel-level maximum is at location 3, but if you want sub-pixel location (eq. by fitting quadratic function) you would neighbourhood of maximum location (i.e. locations 2, 3, 4 with responses 2, 3, 1) and you would obtained that the sub-pixel maximum is "somewhere like 2.8" with value "like 3.1"  (just guessing here, I did not compute that).
This make sense when the response map is computed on features that have smaller spatial resolution than the image, because you then need to scale the maximum location and the sub-pixel localization will give you more accurate results.

**Comment by dafeige01** [comment]
Hi, Thanks a lot for your kind reply and&nbsp;explanation. I am really interested in this problem,&nbsp; and want to know more details. Could you provide any papers or reference?


Best wishes！


yours



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vojirt/kcf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vojirt/kcf] What is the principle of this function——cv::Point2f KCF_Tracker::sub_pixel_peak？ (Issue #32)





 
Hi, it finds sub pixel location of the maximum response in the correlation map by fitting polynomial (of second order) to the neighbourhood of the pixel-level maximum location. For example, consider 1D case, you have
 responses  : 1 2 2 3 1
 at locations: 0 1 2 3 4
 pixel-level maximum is at location 3, but if you want sub-pixel location (eq. by fitting quadratic function) you would neighbourhood of maximum location (i.e. locations 2, 3, 4 with responses 2, 3, 1) and you would obtained that the sub-pixel maximum is "somewhere like 2.8" with value "like 3.1"  (just guessing here, I did not compute that).
 This make sense when the response map is computed on features that have smaller spatial resolution than the image, because you then need to scale the maximum location and the sub-pixel localization will give you more accurate results.

**Comment by vojirt** [comment]
Hi, here is a [paper](https://cmp.felk.cvut.cz/~vojirtom/pdfs/cvpr2017.pdf) on correlation tracking that I co-authored. Look at the `Related Work` section for inspiration and dig deeper (especially ref [19] is the paper this repo is based on) :)
Also look up the publications of J.F. Henriques and M. Danelljan, they did lot of great work in this field.
Cheers!
